# Generated by Django 4.2.7 on 2023-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(db_index=True, default='example@example.com', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
