# Generated by Django 4.1.4 on 2023-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_login_email_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
